[package]
name = "nhs_hours_tracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = {version = "0.2.4",default-features=false, features = ["backend-gl-all","std","compat-0-2-0"]}
rusqlite = {version = "0.27.0", features = ["bundled-full"]}
libsqlite3-sys = "0.24.2"
native-dialog = "0.6.3"
csv = "1.1"
serde = {version = "1.0.139", features = ["derive"]}
chrono = "0.4.19"
docx-rs = "0.4.1"

[build-dependencies]
slint-build = "0.2.4"

